# -*- coding: utf-8 -*-
"""bard chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VPw2lGkznAeXW93Sy_-FkQS2qbhDUEr8
"""

import google.generativeai as genai

global apikey
with open('API_KEY.txt', 'r') as f:
    apikey = f.read()

genai.configure(api_key=apikey)
model = genai.GenerativeModel('gemini-pro')

query = input("How can I help you today?\n")
response = model.generate_content(query)
print(response.text)
while (1>0):
  query = input(">> ")
  response = model.generate_content(query)
  print(response.text)

